---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure directories we need exist.
  file:
    path: "{{ lv.path }}"
    state: directory
    owner: root
    group: wheel
    mode: "0755"
  become: true
  loop:
    - path: "/etc/ansible"
    - path: "/usr/local/etc"
  loop_control:
    loop_var: lv

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link
