---
- name: install
  include_tasks: git-install.{{ ansible_os_family }}.yml

- name: github host keys
  blockinfile:
    block: |
      # via `ssh-keyscan github.com`
      # github.com:22 SSH-2.0-babeld-33961236
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      # github.com:22 SSH-2.0-babeld-33961236
      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
      # github.com:22 SSH-2.0-babeld-33961236
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    create: true
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: gitconfig
  community.general.git_config:
    name: "{{ lv.name }}"
    scope: "{{ lv.scope }}"
    value: "{{ lv.value }}"
    state: "{{ lv.state | default('present') }}"
  become: true
  loop:
    # To avoid cross-platform line-endings pain, force all clones to use LF line-endings.
    - { scope: system, name: core.eol, value: lf }
    - { scope: system, name: core.autocrlf, value: false }
    - { scope: system, name: core.safecrlf, value: false }
  loop_control:
    loop_var: lv

- name: user-level gitconfig
  copy:
    src: user.gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: user-level git ignore
  copy:
    src: user.gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore.user"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
