---
- name: sudo
  include_tasks: sudo.{{ ansible_os_family }}.yml

- name: ansible
  import_tasks: ansible-setup.yml

- name: platform-specific baseline
  include_tasks: package-manager.{{ ansible_os_family }}.yml

- name: ssh
  import_tasks: ssh-setup.yml

- name: git
  import_tasks: git.yml
