---
- name: typing and keyboard
  block:
    - name: Disable auto correct
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
    - name: Disable smart quotes
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticQuoteSubstitutionEnabled
        type: bool
        value: false
    - name: Disable smart dashes
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticDashSubstitutionEnabled
        type: bool
        value: false
    - name: Disable automatic capitalization
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticCapitalizationEnabled
        type: bool
        value: false
    - name: Set a fast initial keyboard repeat rate
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: 20
    - name: Set a fast keyboard repeat rate
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: 1

- name: screen-capture
  block:
    - name: Set screen capture folder to Downloads
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "${HOME}/Downloads"
    - name: "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: type
        type: string
        value: "png"
    - name: Disable shadow in screenshots
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: disable-shadow
        type: bool
        value: true

- name: finder
  block:
    - name: "Do not show Desktop (Icons)"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: CreateDesktop
        type: bool
        value: FALSE
    - name: "Finder: allow quitting via ? + Q; doing so will also hide desktop icons"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: QuitMenuItem
        type: bool
        value: true
    - name: "Set home folder as the default location for new Finder windows pt1"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: "PfLo"
    - name: "Set home folder as the default location for new Finder windows pt2"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: "file://${HOME}/"
    - name: "Show icons for external hard drives on the desktop"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowExternalHardDrivesOnDesktop
        type: bool
        value: true
    - name: "Show icons for hard drives on the desktop"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowHardDrivesOnDesktop
        type: bool
        value: true
    - name: "Show icons for servers on the desktop"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowMountedServersOnDesktop
        type: bool
        value: true
    - name: "Show icons for removable media on the desktop"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowRemovableMediaOnDesktop
        type: bool
        value: true
    - name: "Finder: show hidden files by default"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true
    - name: "Finder: show all filename extensions"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
    - name: "Finder: show status bar"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowStatusBar
        type: bool
        value: true
    - name: "Finder: allow text selection in Quick Look"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: QLEnableTextSelection
        type: bool
        value: true
    - name: "Display full POSIX path as Finder window title"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXShowPosixPathInTitle
        type: bool
        value: true
    - name: "When performing a search, search the current folder by default"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXDefaultSearchScope
        type: string
        value: "SCcf"
    - name: "Disable the warning when changing a file extension"
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXEnableExtensionChangeWarning
        type: bool
        value: false
    - name: "Enable spring loading for directories"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.springing.enabled
        type: bool
        value: true
    - name: "Remove the spring loading delay for directories"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.springing.delay
        type: float
        value: 0.1
    - name: "Avoid creating .DS_Store files on network volumes"
      community.general.osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true

- name: dock
  block:
    - name: Automatically hide and show the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true

    - name: Don't show recent applications in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: Speed up Mission Control animations
      community.general.osx_defaults:
        domain: com.apple.dock
        key: expose-animation-duration
        type: float
        value: 0.15
