---
- name: install XCode (takes ~tens of minutes)
  block:
    - name: make download cache
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.cache/xcode-installers"
        mode: "0774"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
    - name: download XCode
      get_url:
        # https://stackoverflow.com/questions/10335747/how-to-download-xcode-dmg-or-xip-file
        # Didn't need an Apple Developer account; just iCloud/Apple.
        url: https://download.developer.apple.com/Developer_Tools/Xcode_{{ xcode_version }}/Xcode_{{ xcode_version }}.xip
        dest: "{{ ansible_env.HOME }}/.cache/xcode-installers/Xcode_{{ xcode_version }}.xip"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
    - name: install XCode
      import_role:
        name: install_xcode
      vars:
        xcode_xip_location: "{{ ansible_env.HOME }}/.cache/xcode-installers/Xcode_{{ xcode_version }}.xip"
        xcode_major_version: "{{ xcode_version | split('.')[0] }}"
    - name: activate new XCode Developer directory
      become: true
      command: xcode-select --switch /Applications/Xcode.app/Contents/Developer
      changed_when: false

# homebrew requires the XCode command-line tools, so happens after XCode.
- name: install homebrew package manager
  block:
    # It's extremely useful to allow the homebrew installation to be multi-user.
    # https://www.codejam.info/2021/11/homebrew-multi-user.html
    - name: create homebrew user
      ansible.builtin.user:
        name: brew
        comment: Homebrew https://brew.sh
        group: admin
    - name: install homebrew
      import_role:
        name: geerlingguy.mac.homebrew
      vars:
        homebrew_user: brew
        homebrew_group: admin
    - name: alias for brew usage to shell configs
      lineinfile:
        line: alias brew='sudo -Hu brew brew'
        path: "{{ lv.path }}"
        create: true
      loop:
        # - path: "{{ ansible_env.HOME }}/.zshrc"
        - path: "{{ ansible_env.HOME }}/.aliases"
      loop_control:
        loop_var: lv

- name: make a bin directory
  file:
    state: directory
    path: /usr/local/bin
    owner: root
    group: wheel
    mode: "0755"

- name: install other necessary software
  community.general.homebrew:
    name:
      # Install a more recent bash to avoid using the ancient pre-GPL one that Apple ships with.
      - bash
  become: true
  become_user: brew

- name: install rosetta when M* so we can run x86_64 Intel binaries
  when: ansible_architecture == "arm64"
  command: >
    softwareupdate --install-rosetta --agree-to-license
