---
- name: install XCode (takes ~tens of minutes)
  block:
    - name: make download cache
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.cache/xcode-installers"
        mode: "0774"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
    - name: download XCode
      get_url:
        # https://stackoverflow.com/questions/10335747/how-to-download-xcode-dmg-or-xip-file
        # Didn't need an Apple Developer account; just iCloud/Apple.
        url: https://download.developer.apple.com/Developer_Tools/Xcode_{{ xcode_version }}/Xcode_{{ xcode_version }}.xip
        dest: "{{ ansible_env.HOME }}/.cache/xcode-installers/Xcode_{{ xcode_version }}.xip"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
    - name: install XCode
      import_role:
        name: install_xcode
      vars:
        xcode_xip_location: "{{ ansible_env.HOME }}/.cache/xcode-installers/Xcode_{{ xcode_version }}.xip"
        xcode_major_version: "15"
    - name: activate new XCode Developer directory
      become: true
      command: xcode-select --switch /Applications/Xcode.app/Contents/Developer
      changed_when: false

# homebrew requires the XCode command-line tools, so happens after XCode.
- name: install homebrew package manager
  block:
    # It's extremely useful to allow the homebrew installation to be multi-user.
    # https://www.codejam.info/2021/11/homebrew-multi-user.html
    - name: create homebrew user
      ansible.builtin.user:
        name: brew
        comment: Homebrew https://brew.sh
        group: staff
        groups:
          # So that brew can write apps into /Applications
          - admin
          - wheel
        create_home: true
        password: "{{ baseline_brew_password }}"
      become: true

    - name: allow brew user to passwordless sudo
      community.general.sudoers:
        name: allow-brew-passwordless-sudo
        state: present
        user: "brew"
        commands: ALL
      become: true

    - name: allow current user to sudo as homebrew user and run brew
      community.general.sudoers:
        name: allow-{{ ansible_user_id }}-to-do-as-brew
        state: present
        user: "{{ ansible_user_id }}"
        runas: brew
        commands: /opt/homebrew/bin/brew
      become: true

    - name: install homebrew
      import_role:
        name: geerlingguy.mac.homebrew
      vars:
        homebrew_user: brew
        homebrew_group: admin
      become: true
      become_user: brew

    - name: alias for brew usage to shell configs
      lineinfile:
        line: alias brew='sudo -Hu brew brew'
        path: "{{ lv.path }}"
        create: true
      loop:
        # - path: "{{ ansible_env.HOME }}/.zshrc"
        - path: "{{ ansible_env.HOME }}/.aliases"
      loop_control:
        loop_var: lv

    # So that the homebrew has the totality of the underlying git repo...
    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      become: true
      become_user: brew

- name: make a bin directory
  file:
    state: directory
    path: /usr/local/bin
    owner: root
    group: wheel
    mode: "0755"

- name: install other necessary software
  community.general.homebrew:
    name:
      # Install a more recent bash to avoid using the ancient pre-GPL one that Apple ships with.
      - bash
  become: true
  become_user: brew

- name: Make newer bash default for root
  ansible.builtin.user:
    name: root
    shell: "{{ homebrew_prefix }}/bin/bash"
  become: true
  tags: [root, shell]

- name: install rosetta when M* so we can run x86_64 Intel binaries
  when: ansible_architecture == "arm64"
  command: >
    softwareupdate --install-rosetta --agree-to-license
