---
- name: make .ssh
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ ansible_user_id }}"
    group: "{{ user_group }}"
  with_items:
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.ssh/multiplex"

- name: ssh config file
  template:
    src: ssh_config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
