---
- name: make .ssh
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  with_items:
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.ssh/multiplex"

- name: ssh config file
  template:
    src: ssh_config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Set proper permissions on ~/.ssh/authorized_keys
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/authorized_keys"
    state: touch
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
