---
# Do sudo using Touch ID
- name: Set sudo via Touch ID if not setup
  blockinfile:
    block: 'auth       sufficient     pam_tid.so'
    path: "/etc/pam.d/sudo_local"
    owner: root
    group: "{{ root_group }}"
    mode: "0644"
    create: true
  become: true
