# https://github.com/ohmyzsh/ohmyzsh/issues/11111
export ZSH_DISABLE_COMPFIX=true

if [[ -d "${HOME}/.zsh.before" ]]; then
  for config_file in "${HOME}"/.zsh.before/*.zsh; do
    source "${config_file}"
  done
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-${HOME}}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-"${HOME}"}/.zprezto/init.zsh"
fi

if [[ -d "${HOME}/.zsh.after" ]]; then
  for config_file in "${HOME}"/.zsh.after/*.zsh; do
    source "${config_file}"
  done
fi
