---
- hosts: all
  connection: local
  gather_facts: true

  vars_files:
    - vars/default.yml  # overridden by include_vars below
    - secrets.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - vars/{{ ansible_os_family }}.yml
        - vars/default.yml
      tags: [always]

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      when: "{{ debug | default('false') }}"

  roles:
    - role: baseline
      tags: [baseline]
      vars:
        baseline_brew_password: "{{ brew_password }}"
    - role: zsh
      tags: [shell]
    - role: vscode
      tags: [editor, vscode]

  tasks:
    - import_tasks: "tasks/screensaver.yml"
      tags: [screensaver]
    - import_tasks: tasks/python-ecosystem.yml
      tags: [python]
