---
- hosts: all
  connection: local
  gather_facts: true

  vars_files:
    - vars/default.yml  # overridden by include_vars below
    - vars/improbable.yml
    - vars/secrets.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - vars/{{ ansible_os_family }}.yml
        - vars/default.yml
      tags: [always]

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      when: "{{ debug | default('false') }}"

  roles:
    - role: geerlingguy.homebrew
      tags: [homebrew]

  tasks:
    - import_tasks: tasks/ansible-setup.yml
      tags: [ansible]
    - import_tasks: tasks/ssh-setup.yml
      tags: [ssh]
    - import_tasks: tasks/shell-setup.yml
      tags: [shell]
    # git-setup comes after shell-setup because it overrides things done there.
    - import_tasks: tasks/git-setup.yml
      tags: [git]
    - import_tasks: tasks/config-setup.yml
      tags: [config]
    - import_tasks: tasks/kube.yml
      tags: [kube, kubernetes]
    - import_tasks: tasks/python-ecosystem.yml
      tags: [python]
