---
- hosts: all
  connection: local

  vars_files:
    - vars/default.yml  # overridden by include_vars below
    - vars/improbable.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - vars/{{ ansible_os_family }}.yml
        - vars/default.yml
      tags: [always]

  roles:
    - role: geerlingguy.homebrew
      tags: [homebrew]

  tasks:
    - import_tasks: tasks/ansible-setup.yml
      tags: [ansible]
    - import_tasks: tasks/ssh-setup.yml
      tags: [ssh]
    - import_tasks: tasks/shell-setup.yml
      tags: [shell]
    # git-setup comes after shell-setup because it overrides things done there.
    - import_tasks: tasks/git-setup.yml
      tags: [git]
    - import_tasks: tasks/config-setup.yml
      tags: [config]
