---
collections:
  - name: community.general
  - name: geerlingguy.mac
roles:
  - name: gantsign.visual-studio-code-extensions
    version: 2.2.0
  - src: gotmax23.github_cli
    version: v0.3.0
  - src: https://github.com/elliotweiser/ansible-osx-command-line-tools
    version: "2.3.0"
    name: elliotweiser.osx-command-line-tools
  - src: https://github.com/macstadium/ansible-role-xcode
    # at-the-time master@HEAD
    version: 68ce8fe306ea6d060063ab881cc1a3fdb72c9882
    name: install_xcode

