---
- name: config directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.config/direnv"
    - "{{ ansible_user_dir }}/.config/gitk"
    - "{{ ansible_user_dir }}/.config/yamllint"

- name: yamllint
  template:
    src: yamllint.config.j2
    dest: "{{ ansible_user_dir }}/.config/yamllint/config"
