---
# http://krypted.com/mac-security/mac-setting-screen-saver-from-the-cli/
- name: make tmpdir
  tempfile:
    state: directory
  register: tempdir

- name: unzip Aerial installer
  unarchive:
    src: "https://github.com/JohnCoates/Aerial/releases/download/v{{ aerial_version }}/Aerial.saver.zip"
    dest: "{{ tempdir.path }}"
    remote_src: yes

- name: run Aerial
  command: "open {{ tempdir.path }}/Aerial.saver"
  args:
    creates: "/Library/Screen Savers/Aerial.saver"

- name: set up lock screen timer
  command: "defaults -currentHost write com.apple.screensaver idleTime {{ screen_lock_time_seconds }}"
