---
- name: Check if YADR is installed
  stat: 
    path: ~/.yadr
  register: yadr_dir

- name: download YADR
  get_url: 
    url: https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh
    dest: /tmp/yadr_install.sh
    mode: 0755
  when: yadr_dir.stat.exists == false

- name: install YADR
  command: bash -c 'echo yes | /tmp/yadr_install.sh'
  args:
    creates: ~/.yadr
  when: yadr_dir.stat.exists == false

# Unnecessary since Catalina made zsh default
- name: Set the user shell to zsh
  when: ansible_os_family == 'Darwin'
  user: 
    name: "{{ ansible_ssh_user }}"
    shell: /bin/zsh
  become: true

- name: Remove bogus line from .vimrc
  lineinfile:
    dest: ~/.vimrc
    state: absent
    regexp: "^set list listchars"

- name: Debian-isms
  when: ansible_distribution == 'Debian'
  block:
    - lineinfile:
        dest: ~/.zprofile
        line: "export LC_CTYPE='en_US.UTF-8'"

    - lineinfile: 
        dest: ~/.zprofile
        line: "export LANG='en_US.UTF-8'"

    - lineinfile:
        dest: ~/.zprofile
        line: "export LANGUAGE='en_US.UTF-8'"

- name: delete defaults
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ ansible_user_dir }}/.zsh.before"
    - "{{ ansible_user_dir }}/.zsh.after"
    - "{{ ansible_user_dir }}/.zsh.prompts"

- name: symlink in dropbox
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "{{ ansible_user_dir }}/Dropbox/profiles/osx/.zsh.before", dest: "{{ ansible_user_dir }}/.zsh.before"}
    - {src: "{{ ansible_user_dir }}/Dropbox/profiles/osx/.zsh.after", dest: "{{ ansible_user_dir }}/.zsh.after"}
    - {src: "{{ ansible_user_dir }}/Dropbox/profiles/osx/.zsh.prompts", dest: "{{ ansible_user_dir }}/.zsh.prompts"}

- name: fix vim shell prompt
  file:
    state: absent
    path: "{{ ansible_user_dir }}/.inputrc"

- name: shell aliases
  template:
    src: dot-aliases.j2
    dest: "{{ ansible_user_dir }}/.aliases"
