---
- name: software via brew
  community.general.homebrew_cask:
    name: "{{ lv.name }}"
    state: "{{ lv.state | default('present') }}"
  loop:
    - name: visual-studio-code
  loop_control:
    loop_var: lv
  become: true
  become_user: brew
