---
- name: install visual studio code
  include_tasks: install.{{ ansible_os_family }}.yml

- name: install vscode extensions
  include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ lookup('env', 'USER') }}"
        visual_studio_code_extensions: "{{ vscode_extensions }}"
    visual_studio_code_extensions_dependencies: []
