---
- name: install
  include_tasks: kubernetes-install.{{ ansible_os_family }}.yml

- name: kubectl completion
  blockinfile:
    block: |
      # https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#optional-kubectl-configurations-and-plugins
      source <(kubectl completion zsh)
    path: "{{ ansible_env.HOME }}/.zsh.after/kubectl.zsh"
    create: true
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
