---
# https://github.com/sharkdp/bat

- name: install
  include_tasks: bat-install.{{ ansible_os_family }}.yml

- name: Install themes for bat
  ansible.builtin.command: "bat cache --build"
  changed_when: false

# https://github.com/junegunn/fzf#preview-window
- name: fzf preview with bat
  blockinfile:
    block: |
      alias fpb="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
      alias cat='bat --theme=$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo "default" || echo "zenburn")'
    path: "{{ ansible_env.HOME }}/.aliases"
    create: true
