---
- name: install
  include_tasks: "zsh-install.{{ ansible_os_family }}.yml"

- name: Configure shells
  become: true
  tags: shell
  block:
    - name: Make additional shells available
      ansible.builtin.blockinfile:
        path: /etc/shells
        block: |
          {{ homebrew_prefix }}/bin/bash
          {{ homebrew_prefix }}/bin/zsh
    - name: Make zsh default for user
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: "/bin/zsh"

- name: prezto
  block:
    - name: fetch prezto
      git:
        repo: "https://github.com/sorin-ionescu/prezto.git"
        dest: "{{ ansible_env.HOME }}/.zprezto"
        recursive: true
        version: HEAD
      become_user: "{{ ansible_user_id }}"

    - name: backup and link zsh config files
      include_tasks: zsh_backup_and_link.yml
      loop:
        - file: "zlogin"
        - file: "zlogout"
        - file: "zprofile"
        - file: "zshenv"
      loop_control:
        loop_var: lv

    - name: local configuration directories
      file:
        state: directory
        path: "{{ lv.path }}"
      loop:
        - path: "{{ ansible_env.HOME }}/.zsh.before"
        - path: "{{ ansible_env.HOME }}/.zsh.after"
      loop_control:
        loop_var: lv

    - name: blank .zsh.before
      file:
        state: file
        path: "{{ ansible_env.HOME }}/.zsh.before/blank.zsh"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

    - name: homebrew shellenv
      blockinfile:
        block: |
          # homebrew activation
          eval "$(/opt/homebrew/bin/brew shellenv)"
        path: "{{ ansible_env.HOME }}/.zsh.after/homebrew.zsh"
        create: true
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

- name: zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: preztorc
  template:
    src: preztorc.j2
    dest: "{{ ansible_env.HOME }}/.zpreztorc"

- name: prompt
  copy:
    src: prompt.zsh
    dest: "{{ ansible_env.HOME }}/.zsh.after/prompt.zsh"

- name: aliases
  lineinfile:
    line: '[[ -r "${HOME}/.aliases" ]] && source "${HOME}/.aliases"'
    path: "{{ ansible_env.HOME }}/.zsh.after/aliases.zsh"
    create: true

- name: completion
  block:
    - name: zsh completion cache dir
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.cache/zsh"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

    - name: config file
      copy:
        src: completion.zsh
        dest: "{{ ansible_env.HOME }}/.zsh.after/completion.zsh"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

- name: Fix permissions for zsh
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
  loop:
    - "{{ homebrew_prefix }}/share"
    - "{{ homebrew_prefix }}/share/zsh"
    - "{{ homebrew_prefix }}/share/zsh/site-functions"

- name: tmux
  import_tasks: tmux.yml

- name: fzf
  import_tasks: fzf.yml

- name: ag
  import_tasks: ag.yml

- name: bat
  import_tasks: bat.yml

- name: direnv
  import_tasks: direnv.yml

- name: terminal
  import_tasks: terminal.yml
