---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - direnv
  - git
  - git-crypt
  # - go # not at work because puppet
  - gpg
  - hub
  - httpie
  - iperf
  - kubernetes-cli
  - libevent
  - nmap
  - node
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - pyenv
  - rbenv
  - readline
  - ruby-build
  - sqlmap
  - watch
  - wget
  - wrk
  - xhyve
  - xz
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - balenaetcher
  - chromedriver
  - docker
  - docker-completion
  - docker-compose
  - docker-compose-completion
  - dropbox
  - firefox
  - goland
  # - google-chrome
  - google-cloud-sdk
  - handbrake
  - hashcat
  - java8
  - joplin
  - licecap
  - macvim
  - meld
  - microsoft-remote-desktop-beta
  - minikube
  - postman
  - quicksilver
  - rescuetime
  - slack
  - spotify
  - steam
  - steamcmd
  - sublime-text
  - vagrant
  - visual-studio-code
  - zoom
