---
downloads: ~/.ansible-downloads/

nerd_fonts:
  - JetBrainsMono
  - SourceCodePro

python_global_version: "3.10.7"
python_versions:
  - "3.10.7"

root_group: root

screen_lock_time_seconds: 120

vscode_extensions:
  - 4ops.packer
  - aaron-bond.better-comments
  - adamhartford.vscode-base64
  - bazelbuild.vscode-bazel
  - BazelBuild.vscode-bazel
  - bbenoist.nix
  - bbenoist.Nix
  - bbenoist.vagrant
  - be5invis.toml
  - bierner.markdown-mermaid
  - bungcip.better-toml
  - caarlos0.language-prometheus
  - cameron.vscode-pytest
  - castwide.solargraph
  - dannymidnight.vscode-buildkite
  - davidanson.vscode-markdownlint
  - DavidAnson.vscode-markdownlint
  - dawidd6.debian-vscode
  - dbaeumer.vscode-eslint
  - DevonDCarew.bazel-code
  - dotjoshjohnson.xml
  - DotJoshJohnson.xml
  - eamodio.gitlens
  - editorconfig.editorconfig
  - emilast.logfilehighlighter
  - exiasr.hadolint
  - fabiospampinato.vscode-diff
  - fcrespo82.markdown-table-formatter
  - flesler.url-encode
  - fnando.linter
  - fredwangwang.vscode-hcl-format
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - GitHub.vscode-pull-request-github
  - golang.go
  - googlecloudtools.cloudcode
  - gruntfuggly.todo-tree
  - Gruntfuggly.todo-tree
  - hangxingliu.vscode-systemd-support
  - hashicorp.hcl
  - hashicorp.terraform
  - heptio.jsonnet
  - iliazeus.vscode-ansi
  - jetmartin.bats
  - jnbt.vscode-rufo
  - lextudio.restructuredtext
  - maelvalais.autoconf
  - marklarah.pre-commit-vscode
  - MarkLarah.pre-commit-vscode
  - medo64.render-crlf
  - mindaro-dev.file-downloader
  - moshfeu.compare-folders
  - ms-azuretools.vscode-azureresourcegroups
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - ms-dotnettools.vscode-dotnet-runtime
  - ms-mssql.mssql
  - ms-python.debugpy
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-slideshow
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-wsl
  - ms-vscode.azure-account
  - ms-vscode.cmake-tools
  - ms-vscode.cpptools
  - ms-vscode.cpptools-extension-pack
  - ms-vscode.cpptools-themes
  - ms-vscode.makefile-tools
  - ms-vscode.powershell
  - ms-vsliveshare.vsliveshare
  - mtxr.sqltools
  - orta.vscode-jest
  - pascalreitermann93.vscode-yaml-sort
  - peterj.proto
  - rafaelmaiolla.diff
  - redhat.java
  - redhat.vscode-yaml
  - rubymaniac.vscode-direnv
  - ryu1kn.partial-diff
  - s3ramsay.vscode-gtm
  - shan.code-settings-sync
  - Shan.code-settings-sync
  - shopify.ruby-lsp
  - sidneys1.gitconfig
  - simonsiefke.svg-preview
  - slevesque.perforce
  - slevesque.vscode-zipexplorer
  - SonarSource.sonarlint-vscode
  - sourcegraph.sourcegraph
  - stkb.rewrap
  - streetsidesoftware.code-spell-checker
  - timonwong.shellcheck
  - trond-snekvik.simple-rst
  - tsandall.opa
  - twxs.cmake
  - tyriar.sort-lines
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-pack
  - wayou.vscode-todo-highlight
  - wengerk.highlight-bad-chars
  - wholroyd.jinja
  - wingrunr21.vscode-ruby
  - xrc-inc.jsonnet-formatter
  - zhouronghui.propertylist
  - zxh404.vscode-proto3
