---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

homebrew_installed_packages:
  - adns
  - autoconf
  - automake
  - awscli
  - bash-completion
  - bison
  - buildkite-agent
  - cmake
  - coreutils
  - ctags
  - direnv
  - docker-compose
  - gdbm
  - gettext
  - ghi
  - git
  - git-crypt
  - gmp
  - gnu-sed
  - gnupg
  - gnutls
  - go
  - hashcat
  - httpie
  - hub
  - hugo
  - icu4c
  - iperf
  - jq
  - jsonnet
  - kubernetes-cli
  - libassuan
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn2
  - libksba
  - libressl
  - libtasn1
  - libunistring
  - libusb
  - libyaml
  - llvm@4
  - md5sha1sum
  - mysql
  - ncurses
  - nettle
  - nmap
  - node
  - npth
  - nvm
  - oniguruma
  - openssl
  - openssl@1.1
  - p11-kit
  - packer
  - parallel
  - pcre
  - pcre2
  - pinentry
  - pkg-config
  - protobuf
  - pv
  - pyenv
  - python
  - python@2
  - rbenv
  - readline
  - reattach-to-user-namespace
  - ruby-build
  - shellcheck
  - sqlite
  - sqlmap
  - ssh-copy-id
  - tfenv
  - the_silver_searcher
  - tmux
  - tree
  - unbound
  - watch
  - wget
  - wrk
  - xhyve
  - xz
  - yarn
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - buildkite/buildkite

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - balenaetcher
  - charles
  - chromedriver
  - controlplane
  - datagrip
  - docker
  - dropbox
  - firefox
  - goland
  # - google-chrome
  - google-cloud-sdk
  - handbrake
  # - java8
  - joplin
  - licecap
  - macvim
  - meld
  # - microsoft-remote-desktop-beta
  - minikube
  - p4v
  - postman
  - quicksilver
  - rescuetime
  - slack
  - spotify
  - steam
  - steamcmd
  - sublime-text
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - zoom
  - zoomus
