---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_sudoers: true
configure_terminal: true
configure_osx: true

homebrew_installed_packages:
  - adns
  - autoconf
  - automake
  - awscli
  - bash-completion
  - bison
  - buildkite-agent
  - cmake
  - coreutils
  - ctags
  - direnv
  - docker-compose
  - dotnet
  - gdbm
  - gettext
  - gh
  - ghi
  - git
  - git-crypt
  - gmp
  - gnu-sed
  - gnupg
  - gnutls
  - go
  - hashcat
  - httpie
  - hub
  - hugo
  - icu4c
  - iperf
  - jq
  - jsonnet
  - kubernetes-cli
  - kubectx
  - libassuan
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn2
  - libksba
  - libressl
  - libtasn1
  - libunistring
  - libusb
  - libyaml
  # - llvm@4
  # - md5sha1sum # conflicts with coreutils
  - mysql
  - ncurses
  - nettle
  - nmap
  - node
  - npth
  - nvm
  - oniguruma
  - openssl
  - openssl@1.1
  - p11-kit
  - packer
  - parallel
  - pcre
  - pcre2
  - pinentry
  - pinentry-mac
  - pkg-config
  - protobuf
  - pv
  # - pyenv
  # - python
  # - python@2
  - rbenv
  - readline
  - reattach-to-user-namespace
  - ruby-build
  - shellcheck
  - sqlite
  - sqlmap
  - ssh-copy-id
  - tfenv
  - the_silver_searcher
  - tmux
  - tree
  - unbound
  - watch
  - wget
  - wrk
  - xhyve
  - xz
  - yarn
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - buildkite/buildkite

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - balenaetcher
  - charles
  - chromedriver
  - controlplane
  - datagrip
  - docker
  - dropbox
  - firefox
  - goland
  - google-chrome
  - google-cloud-sdk
  - handbrake
  # - java8 # error
  - joplin
  - licecap
  - macvim
  - meld
  # - microsoft-remote-desktop # no cask?
  - p4v
  - postman
  - quicksilver
  # - rescuetime # checksum mismatch
  - slack
  - spotify
  - steam
  - steamcmd
  - sublime-text
  - vagrant
  # - virtualbox # error
  - visual-studio-code
  - vlc
  - zoom
  - zoomus

vscode_extensions:
  - aaron-bond.better-comments
  - BazelBuild.vscode-bazel
  - bbenoist.Nix
  - bbenoist.vagrant
  - bungcip.better-toml
  - caarlos0.language-prometheus
  - dannymidnight.vscode-buildkite
  - DavidAnson.vscode-markdownlint
  - DevonDCarew.bazel-code
  - DotJoshJohnson.xml
  - eamodio.gitlens
  - exiasr.hadolint
  - fcrespo82.markdown-table-formatter
  - GitHub.vscode-pull-request-github
  - golang.go
  - Gruntfuggly.todo-tree
  - hangxingliu.vscode-systemd-support
  - hashicorp.terraform
  - heptio.jsonnet
  - jetmartin.bats
  - lextudio.restructuredtext
  - maelvalais.autoconf
  - MarkLarah.pre-commit-vscode
  - medo64.render-crlf
  - moshfeu.compare-folders
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - ms-mssql.mssql
  - ms-python.python
  - ms-vscode.powershell
  - ms-vsliveshare.vsliveshare
  - mtxr.sqltools
  - rafaelmaiolla.diff
  - redhat.vscode-yaml
  - rupisaini.vscode-ansible-linter
  - ryu1kn.partial-diff
  - s3ramsay.vscode-gtm
  - Shan.code-settings-sync
  - sidneys1.gitconfig
  - slevesque.perforce
  - SonarSource.sonarlint-vscode
  - sourcegraph.sourcegraph
  - stkb.rewrap
  - timonwong.shellcheck
  - tsandall.opa
  - vscoss.vscode-ansible
  - wayou.vscode-todo-highlight
  - wengerk.highlight-bad-chars
  - wholroyd.jinja
  - xrc-inc.jsonnet-formatter
  - zhouronghui.propertylist
  - zxh404.vscode-proto3

screen_lock_time_seconds: 120
